### PR TITLE
added spanish suits

### PR DESCRIPTION
**Pull request by stewadan**
I added the spanish suits to the Suit model, the 4 suits are cups, coins, swords and carrots. Carrots is actually called clubs, but we already have a clubs suit for the American version, so i made it carrots. I also upload png images for the cards.

### CODE REVIEW

**Comment by stewadan** [comment]
Oh, i see why its failing, i never updated "clubs" in the spanish test to "carrots"

**Comment by stewadan** [comment]
A little more info, the Spanish cards all range in values from 2-11, with 8, 9 and 10 being the jack king and queen, and 11 being the ace, which appears as a 1 on the cards, but is treated as the Ace in this game.

**Comment by MichaelHilton** [comment]
I just happened to notice this comment in my github feed.  if you look at the assignment specifically the conversation, it says the deck should be treated as follows:
-The Spanish deck option should support a standard Spanish Deck 
    The deck consists of 40 cards, divided into 4 suits: Coins, Cups, Swords and Clubs. 
    Each Suit consists of 1-7, Jack, Knight, and King. The "Ace" is 1, and is low. 

Notice that for this deck, the Ace should be treated at 1 to be correct.

**Comment by stewadan** [comment]
Oh, so for the Spanish deck, the king is the highest, not the Ace?

**Comment by alecmerdler** [comment]
Well done on the images. All tests are passing, and there are no conflicts. Merging.

**Comment by alecmerdler** [comment]
#31 #28

**Pull request merged**
